In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances, paired_distances
from sklearn.metrics import pairwise_distances
import numpy as np
from scipy import spatial

In [54]:
mutational_matrix = pd.read_csv(r'./resources/mut_mat.csv')
reconstructed_matrix = pd.read_csv(r'./resources/reconstructed.csv')
cosmic_catalog = pd.read_csv(r'./resources/cosmic_mutations.csv', delimiter='\t')
contribution_matrix = pd.read_csv(r'./resources/contribution.csv')

In [55]:
mutational_matrix = mutational_matrix.sort_values(by='Somatic Mutation Type', axis=0)
reconstructed_matrix = reconstructed_matrix.sort_values(by='Somatic Mutation Type', axis=0)
cosmic_catalog = cosmic_catalog.sort_values(by='Somatic Mutation Type', axis=0)

In [56]:
cosmic_catalog = cosmic_catalog.loc[:, ~cosmic_catalog.columns.str.contains('^Unnamed')]

In [64]:
my_input = mutational_matrix[['colon1','colon2','colon3','intestine1','intestine2','intestine3','liver1','liver2','liver3']].values
my_reconstructed = reconstructed_matrix[['colon1','colon2','colon3','intestine1','intestine2','intestine3','liver1','liver2','liver3']].values
my_contribution = contribution_matrix[['colon1','colon2','colon3','intestine1','intestine2','intestine3','liver1','liver2','liver3']].values

In [65]:
my_catalog = cosmic_catalog.loc[:, cosmic_catalog.columns.str.contains('^Signature')].values

In [66]:
new_matrix = np.dot(my_catalog, my_contribution)

In [67]:
new_matrix

array([[2.43570841e+00, 7.83385641e+00, 7.48580000e+00, 2.03218122e+00,
        1.19558782e+01, 6.28229539e+00, 4.38073542e+00, 1.39077853e+01,
        3.34314057e+00],
       [1.74975428e+00, 6.26193212e+00, 5.57517257e+00, 1.61026208e+00,
        9.90110143e+00, 5.12803717e+00, 2.66973218e+00, 9.57626995e+00,
        2.09916680e+00],
       [4.32202026e-01, 9.12332162e-01, 7.50128394e-01, 2.78704954e-01,
        1.42239136e+00, 7.33226945e-01, 7.05586048e-01, 2.68851141e+00,
        3.44235741e-01],
       [1.45335359e+00, 5.10361879e+00, 4.73575218e+00, 1.45832806e+00,
        8.01802911e+00, 3.88044085e+00, 2.35352832e+00, 8.71411453e+00,
        2.24827659e+00],
       [5.20773844e-01, 1.51526969e+00, 1.23078095e+00, 6.56121211e-01,
        2.95376765e+00, 1.23757430e+00, 1.74976901e+00, 7.20373815e+00,
        2.08814962e+00],
       [4.73768779e-01, 1.48088947e+00, 1.27932594e+00, 4.71570526e-01,
        2.44405290e+00, 1.33802211e+00, 1.04859351e+00, 3.96108044e+00,
        1.1

In [47]:
my_input

array([3.00010e+00, 1.00000e-04, 2.00010e+00, 1.00000e-04, 1.00000e-04,
       1.00010e+00, 1.00000e-04, 1.00000e-04, 5.00010e+00, 4.00010e+00,
       2.20001e+01, 4.00010e+00, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00010e+00, 6.00010e+00, 1.00000e-04, 4.00010e+00, 6.00010e+00,
       1.00010e+00, 1.00000e-04, 1.00010e+00, 2.00010e+00, 1.00010e+00,
       2.00010e+00, 1.00010e+00, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 7.00010e+00, 2.00010e+00, 1.00001e+01,
       2.00010e+00, 1.00010e+00, 1.00000e-04, 1.00000e-04, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 3.00010e+00, 2.00010e+00, 1.00010e+00,
       1.00010e+00, 2.00010e+00, 1.00010e+00, 4.00010e+00, 2.00010e+00,
       1.00010e+00, 2.00010e+00, 1.00000e-04, 1.00000e-04, 1.00000e-04,
       1.00000e-04, 6.00010e+00, 6.00010e+00, 1.80001e+01, 4.00010e+00,
       1.00010e+00, 1.00000e-04, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 2.00010e+00, 1.00010e+00, 1.000

In [68]:
my_contribution

array([[118.2802532, 434.2443907, 364.1938768,  69.1330279, 566.2289241,
        432.7219254,  19.915174 ,  31.6881887,   2.3983694],
       [  0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          7.2427278,   2.1069603,  13.0898479,   0.       ],
       [  0.       ,   0.       ,   0.       ,   0.       ,  31.0250768,
          0.       ,   0.       ,  66.1514174,  65.3860658],
       [  0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ,  69.0655402,   0.       ],
       [  0.       ,   0.       ,   0.       ,  24.4876642,   0.       ,
          0.       ,  89.9857544, 234.0703336,  15.8573503],
       [  0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ,   0.       ,   0.       ],
       [  0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  13.2743096,   0.       ,   5.9981827],
       [  0.       ,  40.2591665,  58.2421774,  18.6832342,  9

In [87]:
similarity = paired_distances(new_matrix.reshape(-1,1), my_input.reshape(-1,1), metric='manhattan')

In [88]:
np.average(similarity)

1.5375217392027791

In [89]:
np.sum(similarity)

1328.4187826712011

In [27]:
signeR_matrix = pd.read_csv(r'./resources/21_breast_cancers.mutations.txt', delimiter='\t')
signeR_contribution = pd.read_csv(r'./resources/exposures_signeR.csv')
signeR_signatures = pd.read_csv(r'./resources/signatures_signeR.csv')

In [30]:
signeR_matrix = signeR_matrix.loc[:, ~signeR_matrix.columns.str.contains('^Unnamed')].values
signeR_contribution = signeR_contribution.loc[:, ~signeR_contribution.columns.str.contains('^Unnamed')].values
signeR_signatures = signeR_signatures.loc[:, ~signeR_signatures.columns.str.contains('^Unnamed')].values

In [34]:
signeR_reconstructed = np.dot(signeR_signatures, signeR_contribution)

In [49]:
signeR_reconstructed = signeR_reconstructed.transpose()

In [50]:
signeR_reconstructed.shape

(21, 96)

In [48]:
signeR_matrix.shape

(21, 96)

In [75]:
signeR_similarity = paired_distances(signeR_reconstructed.reshape(-1,1), signeR_matrix.reshape(-1,1), metric='manhattan')

In [81]:
np.average(signeR_similarity)

6.383718145214449

In [83]:
np.sum(signeR_similarity)

12869.57578075233