In [1]:
import pandas as pd
import numpy as np

In [2]:
mutational_matrix = pd.read_csv(r'./resources/mut_mat.csv')
reconstructed_matrix = pd.read_csv(r'./resources/reconstructed.csv')
cosmic_catalog = pd.read_csv(r'./resources/cosmic_mutations.csv', delimiter='\t')
contribution_matrix = pd.read_csv(r'./resources/contribution.csv')

In [3]:
mutational_matrix = mutational_matrix.sort_values(by='Somatic Mutation Type', axis=0)
reconstructed_matrix = reconstructed_matrix.sort_values(by='Somatic Mutation Type', axis=0)
cosmic_catalog = cosmic_catalog.sort_values(by='Somatic Mutation Type', axis=0)

In [4]:
cosmic_catalog = cosmic_catalog.loc[:, ~cosmic_catalog.columns.str.contains('^Unnamed')]

In [6]:
my_input = mutational_matrix['colon1'].values
my_reconstructed = reconstructed_matrix['colon1'].values
my_contribution = contribution_matrix['colon1'].values

In [5]:
my_catalog = cosmic_catalog.loc[:, cosmic_catalog.columns.str.contains('^Signature')].values

In [7]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances, paired_distances
from sklearn.metrics import pairwise_distances
import numpy as np

In [8]:
from scipy import spatial

In [9]:
new_matrix = np.dot(np.array(my_catalog), my_contribution)

In [46]:
new_matrix

array([ 2.43570841,  1.74975428,  0.43220203,  1.45335359,  0.52077384,
        0.47376878,  0.17300021,  0.73296185,  5.46150108,  3.2832464 ,
       21.40919377,  2.47597908,  1.21045989,  0.83154941,  0.87077849,
        1.67344259,  5.07785245,  1.78977073,  3.06216992,  3.47946105,
        0.51116139,  0.46429574,  0.57680826,  0.93035966,  2.41802211,
        1.741024  ,  0.46751217,  1.9038047 ,  0.42894207,  0.41767872,
        0.27412932,  0.63074446,  4.76072104,  3.88590631, 12.03642018,
        3.7596822 ,  0.95607359,  1.01286922,  1.00800326,  0.73419302,
        1.21633181,  1.61641786,  1.91744282,  2.0432854 ,  0.12267839,
        0.76807036,  0.64718494,  1.41139788,  2.46703192,  2.12960725,
        0.5723731 ,  2.09144963,  0.40514071,  0.60166742,  0.07079878,
        0.2948486 ,  5.32385166,  6.9567497 , 15.9120744 ,  4.45406693,
        0.44487327,  0.39976302,  0.50825239,  0.59462812,  2.4045706 ,
        2.30742757,  1.67809123,  2.24936078,  0.07209163,  0.24

In [47]:
my_input

array([3.00010e+00, 1.00000e-04, 2.00010e+00, 1.00000e-04, 1.00000e-04,
       1.00010e+00, 1.00000e-04, 1.00000e-04, 5.00010e+00, 4.00010e+00,
       2.20001e+01, 4.00010e+00, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00010e+00, 6.00010e+00, 1.00000e-04, 4.00010e+00, 6.00010e+00,
       1.00010e+00, 1.00000e-04, 1.00010e+00, 2.00010e+00, 1.00010e+00,
       2.00010e+00, 1.00010e+00, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 7.00010e+00, 2.00010e+00, 1.00001e+01,
       2.00010e+00, 1.00010e+00, 1.00000e-04, 1.00000e-04, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 3.00010e+00, 2.00010e+00, 1.00010e+00,
       1.00010e+00, 2.00010e+00, 1.00010e+00, 4.00010e+00, 2.00010e+00,
       1.00010e+00, 2.00010e+00, 1.00000e-04, 1.00000e-04, 1.00000e-04,
       1.00000e-04, 6.00010e+00, 6.00010e+00, 1.80001e+01, 4.00010e+00,
       1.00010e+00, 1.00000e-04, 1.00010e+00, 1.00010e+00, 1.00000e-04,
       1.00000e-04, 1.00010e+00, 2.00010e+00, 1.00010e+00, 1.000

In [17]:
my_contribution

array([118.2802532,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,  17.6194767,
        44.3999353,   0.       ,   4.3229302,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   5.5795102,   0.       ,
         0.       ,   1.3361086,   0.       ,   0.       ,  16.8131646])

In [15]:
similarity = paired_distances(np.array(new_matrix).reshape(-1, 1), np.array(my_input).reshape(-1, 1), metric='manhattan')

In [16]:
np.sum(similarity)

73.91965570731156